/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregistration;
import java.sql.PreparedStatement;

/**
 *
 * @author user
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null); // Set form in center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        UsernameText1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        Enterpw = new javax.swing.JLabel();
        Enter = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RegiterLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginForm");

        Header.setBackground(new java.awt.Color(0, 51, 153));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Student Portal Login Form");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandregistration/world.png"))); // NOI18N
        Header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 80, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\sem 5\\db\\lab14\\login_7856126.png")); // NOI18N
        Header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, 70));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username: ");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 40));

        Welcome.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 0, 204));
        Welcome.setText("Welcome to Login Page!");
        jPanel1.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        Password.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password:");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 30));

        UsernameText1.setBackground(new java.awt.Color(204, 204, 255));
        UsernameText1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        UsernameText1.setToolTipText("Enter your username");
        UsernameText1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UsernameText1.addActionListener(this::UsernameText1ActionPerformed);
        jPanel1.add(UsernameText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 267, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 255));
        jPasswordField1.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        jPasswordField1.setToolTipText("Enter your password");
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 267, -1));

        Enterpw.setBackground(new java.awt.Color(255, 255, 255));
        Enterpw.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enterpw.setForeground(new java.awt.Color(255, 255, 255));
        Enterpw.setText("Enter password");
        jPanel1.add(Enterpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        Enter.setBackground(new java.awt.Color(255, 255, 255));
        Enter.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enter.setForeground(new java.awt.Color(255, 255, 255));
        Enter.setText("Enter username");
        jPanel1.add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        LoginButton.setBackground(new java.awt.Color(0, 51, 255));
        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(102, 102, 255)));
        LoginButton.addActionListener(this::LoginButtonActionPerformed);
        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 119, 34));

        CancelButton.setBackground(new java.awt.Color(255, 51, 51));
        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(255, 102, 102), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51)));
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });
        CancelButton.addActionListener(this::CancelButtonActionPerformed);
        jPanel1.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 119, 34));

        jLabel2.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Don't have an account? ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        RegiterLabel.setBackground(new java.awt.Color(0, 0, 204));
        RegiterLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        RegiterLabel.setForeground(new java.awt.Color(0, 153, 204));
        RegiterLabel.setText("Sign up");
        RegiterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegiterLabelMouseClicked(evt);
            }
        });
        jPanel1.add(RegiterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandregistration/password.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandregistration/Myusername.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 720, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameText1ActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
         String username = UsernameText1.getText().trim();
    String password = String.valueOf(jPasswordField1.getPassword()).trim();

    // Empty field checks
    if (username.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this, "Username is required", "Error", javax.swing.JOptionPane.ERROR_MESSAGE
        );
        UsernameText1.requestFocus();
        return;
    }
    if (username.matches("\\d+")) { // only digits
    javax.swing.JOptionPane.showMessageDialog(
        this, "Username cannot be only digits", "Error", javax.swing.JOptionPane.ERROR_MESSAGE
    );
    UsernameText1.requestFocus();
    return;
     }
    if (password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this, "Password is required", "Error", javax.swing.JOptionPane.ERROR_MESSAGE
        );
        jPasswordField1.requestFocus();
        return;
    }

    // 🔵 Database validation
    try (java.sql.Connection con = DBConnection.getConnection();
         java.sql.PreparedStatement ps =
             con.prepareStatement("SELECT * FROM students WHERE u_username=? AND u_pass=?")) {

        ps.setString(1, username);
        ps.setString(2, password);

        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            javax.swing.JOptionPane.showMessageDialog(
                this, "Login Successful!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            UserManagementForm umf = new UserManagementForm();
            umf.setVisible(true);
            umf.pack();
            umf.setLocationRelativeTo(null);
            this.dispose();

        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this, "Invalid username or password", "Login Failed",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(
            this, "Database error occurred", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
        e.printStackTrace();
    } 
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void RegiterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegiterLabelMouseClicked
        // TODO add your handling code here:
        RegisterForm rgf = new RegisterForm();
        rgf.setVisible(true);
        rgf.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_RegiterLabelMouseClicked

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_CancelButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel Enter;
    private javax.swing.JLabel Enterpw;
    private javax.swing.JPanel Header;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel RegiterLabel;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameText1;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
