/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregistration;

/**
 *
 * @author user
 */
import java.awt.BorderLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

public class RegisterForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterForm.class.getName());

    /**
     * Creates new form RegisterForm
     */
public RegisterForm() {
    initComponents();  
    setupScroll();  

    setSize(560, 500);      // visible window size
    setLocationRelativeTo(null);
    setResizable(false);
    setVisible(true);
}

// ⚡ Add this OUTSIDE the constructor, but still INSIDE the class
private void setupScroll() {

    // MAIN CONTAINER
    JPanel mainPanel = new JPanel(new BorderLayout());

    // jPanel1 = HEADER PANEL (already exists)
    // jPanel2 = FORM PANEL (big content)
    JScrollPane scrollPane = new JScrollPane(jPanel2);
    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    scrollPane.getVerticalScrollBar().setUnitIncrement(16);

    // ADD PANELS
    mainPanel.add(jPanel1, BorderLayout.NORTH);      // HEADER stays on top
    mainPanel.add(scrollPane, BorderLayout.CENTER);  // SCROLL FORM

    // APPLY TO FRAME
    setContentPane(mainPanel);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserprofileIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        jPasswordField_PASS = new javax.swing.JPasswordField();
        Enterpw = new javax.swing.JLabel();
        jTextField_UN = new javax.swing.JTextField();
        Enter = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        jTextField_LN = new javax.swing.JTextField();
        Enter1 = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        Enter2 = new javax.swing.JLabel();
        jTextField_FN = new javax.swing.JTextField();
        Enterpw1 = new javax.swing.JLabel();
        jPasswordField_REPASS = new javax.swing.JPasswordField();
        Password2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        RegisterButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        UserprofileIcon1 = new javax.swing.JLabel();
        emial = new javax.swing.JLabel();
        jTextField_Em = new javax.swing.JTextField();
        Enter3 = new javax.swing.JLabel();
        Username2 = new javax.swing.JLabel();
        jTextField_UN2 = new javax.swing.JTextField();
        Enter4 = new javax.swing.JLabel();
        Username3 = new javax.swing.JLabel();
        jTextField_UN3 = new javax.swing.JTextField();
        Enter5 = new javax.swing.JLabel();
        Username4 = new javax.swing.JLabel();
        jTextField_UN4 = new javax.swing.JTextField();
        Enter6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Student's Registration Form");

        UserprofileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandregistration/registration.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(UserprofileIcon)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserprofileIcon)
                    .addComponent(jLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 80);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setFont(new java.awt.Font("Dubai", 0, 22)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setText("Welcome to Registration Page!");
        jPanel2.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jPasswordField_PASS.setBackground(new java.awt.Color(204, 204, 255));
        jPasswordField_PASS.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        jPasswordField_PASS.setToolTipText("Enter your password");
        jPanel2.add(jPasswordField_PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 230, -1));

        Enterpw.setBackground(new java.awt.Color(255, 255, 255));
        Enterpw.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enterpw.setForeground(new java.awt.Color(255, 255, 255));
        Enterpw.setText("Enter password");
        jPanel2.add(Enterpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, -1, -1));

        jTextField_UN.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_UN.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTextField_UN.setToolTipText("Enter your username");
        jTextField_UN.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_UN.addActionListener(this::jTextField_UNActionPerformed);
        jPanel2.add(jTextField_UN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 230, -1));

        Enter.setBackground(new java.awt.Color(255, 255, 255));
        Enter.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enter.setForeground(new java.awt.Color(255, 255, 255));
        Enter.setText("Enter username");
        jPanel2.add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        Password.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password:");
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, 30));

        Username.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username: ");
        jPanel2.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 40));

        LastName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name");
        jPanel2.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 40));

        jTextField_LN.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_LN.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTextField_LN.setToolTipText("Enter your lastname");
        jTextField_LN.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_LN.addActionListener(this::jTextField_LNActionPerformed);
        jPanel2.add(jTextField_LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 230, -1));

        Enter1.setBackground(new java.awt.Color(255, 255, 255));
        Enter1.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enter1.setForeground(new java.awt.Color(255, 255, 255));
        Enter1.setText("Enter last_name");
        jPanel2.add(Enter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        FirstName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name");
        jPanel2.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 40));

        Enter2.setBackground(new java.awt.Color(255, 255, 255));
        Enter2.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enter2.setForeground(new java.awt.Color(255, 255, 255));
        Enter2.setText("Enter first_name");
        jPanel2.add(Enter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jTextField_FN.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_FN.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTextField_FN.setToolTipText("Enter your first name");
        jTextField_FN.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_FN.addActionListener(this::jTextField_FNActionPerformed);
        jPanel2.add(jTextField_FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 230, -1));

        Enterpw1.setBackground(new java.awt.Color(255, 255, 255));
        Enterpw1.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enterpw1.setForeground(new java.awt.Color(255, 255, 255));
        Enterpw1.setText("Enter password again");
        jPanel2.add(Enterpw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, -1, -1));

        jPasswordField_REPASS.setBackground(new java.awt.Color(204, 204, 255));
        jPasswordField_REPASS.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        jPanel2.add(jPasswordField_REPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 230, -1));

        Password2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Password2.setForeground(new java.awt.Color(255, 255, 255));
        Password2.setText("Retype Pass  ");
        jPanel2.add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 10));

        RegisterButton.setBackground(new java.awt.Color(0, 51, 255));
        RegisterButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegisterButton.setText("Register");
        RegisterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(102, 102, 255)));
        RegisterButton.addActionListener(this::RegisterButtonActionPerformed);
        jPanel2.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 690, 119, 34));

        CancelButton.setBackground(new java.awt.Color(255, 51, 51));
        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(255, 102, 102), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51)));
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });
        CancelButton.addActionListener(this::CancelButtonActionPerformed);
        jPanel2.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 690, 119, 34));

        jLabel2.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Already have an account? ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 750, -1, -1));

        LoginLabel.setBackground(new java.awt.Color(0, 0, 204));
        LoginLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(0, 153, 204));
        LoginLabel.setText("Login");
        LoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLabelMouseClicked(evt);
            }
        });
        jPanel2.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 750, -1, -1));

        UserprofileIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandregistration/man.png"))); // NOI18N
        jPanel2.add(UserprofileIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        emial.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        emial.setForeground(new java.awt.Color(255, 255, 255));
        emial.setText("Your Email: ");
        jPanel2.add(emial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 40));

        jTextField_Em.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_Em.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTextField_Em.setToolTipText("Enter your username");
        jTextField_Em.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_Em.addActionListener(this::jTextField_EmActionPerformed);
        jPanel2.add(jTextField_Em, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 230, -1));

        Enter3.setBackground(new java.awt.Color(255, 255, 255));
        Enter3.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enter3.setForeground(new java.awt.Color(255, 255, 255));
        Enter3.setText("Enter email");
        jPanel2.add(Enter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        Username2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Username2.setForeground(new java.awt.Color(255, 255, 255));
        Username2.setText("Department: ");
        jPanel2.add(Username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, 40));

        jTextField_UN2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_UN2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTextField_UN2.setToolTipText("Enter your username");
        jTextField_UN2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_UN2.addActionListener(this::jTextField_UN2ActionPerformed);
        jPanel2.add(jTextField_UN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 230, -1));

        Enter4.setBackground(new java.awt.Color(255, 255, 255));
        Enter4.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enter4.setForeground(new java.awt.Color(255, 255, 255));
        Enter4.setText("Enter department");
        jPanel2.add(Enter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        Username3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Username3.setForeground(new java.awt.Color(255, 255, 255));
        Username3.setText("Semester:");
        jPanel2.add(Username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 100, 40));

        jTextField_UN3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_UN3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTextField_UN3.setToolTipText("Enter your username");
        jTextField_UN3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_UN3.addActionListener(this::jTextField_UN3ActionPerformed);
        jPanel2.add(jTextField_UN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 230, -1));

        Enter5.setBackground(new java.awt.Color(255, 255, 255));
        Enter5.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enter5.setForeground(new java.awt.Color(255, 255, 255));
        Enter5.setText("Enter semester");
        jPanel2.add(Enter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        Username4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Username4.setForeground(new java.awt.Color(255, 255, 255));
        Username4.setText("CGPA: ");
        jPanel2.add(Username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, 40));

        jTextField_UN4.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_UN4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTextField_UN4.setToolTipText("Enter your username");
        jTextField_UN4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_UN4.addActionListener(this::jTextField_UN4ActionPerformed);
        jPanel2.add(jTextField_UN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 230, -1));

        Enter6.setBackground(new java.awt.Color(255, 255, 255));
        Enter6.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Enter6.setForeground(new java.awt.Color(255, 255, 255));
        Enter6.setText("Enter CGPA");
        jPanel2.add(Enter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 810, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 550, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLabelMouseClicked
        // TODO add your handling code here:
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LoginLabelMouseClicked

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
    String fname = jTextField_FN.getText();
    String lname = jTextField_LN.getText();
    String uname = jTextField_UN.getText();
    String email = jTextField_Em.getText();
    String department = jTextField_UN2.getText();
    String pass = String.valueOf(jPasswordField_PASS.getPassword());
    String re_pass = String.valueOf(jPasswordField_REPASS.getPassword());

    // Basic validation
    if (fname.isEmpty() || lname.isEmpty() || uname.isEmpty() || email.isEmpty()
        || department.isEmpty() || pass.isEmpty() || re_pass.isEmpty()
        || jTextField_UN3.getText().isEmpty() || jTextField_UN4.getText().isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(this,
            "❌ All fields are required",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
   }

    if (!pass.equals(re_pass)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int semester = Integer.parseInt(jTextField_UN3.getText());
        double cgpa = Double.parseDouble(jTextField_UN4.getText());

        java.sql.Connection con = DBConnection.getConnection();
         //Duplicate username check
        String checkQuery = "SELECT u_id FROM students WHERE u_username = ?";
        PreparedStatement checkPs = con.prepareStatement(checkQuery);
        checkPs.setString(1, uname);
        ResultSet rs = checkPs.executeQuery();

        if (rs.next()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Username already exists. Choose another one.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String query = "INSERT INTO students "
                + "(u_fname, u_lname, u_username, u_pass, u_email, u_depart, u_sem, u_cgpa) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, fname);
        ps.setString(2, lname);
        ps.setString(3, uname);
        ps.setString(4, pass);
        ps.setString(5, email);
        ps.setString(6, department);
        ps.setInt(7, semester);
        ps.setDouble(8, cgpa);

        ps.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Registration Successful!");

        new LoginForm().setVisible(true);
        this.dispose();

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semester and CGPA must be numeric");
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Registration Failed");
    } 
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void jTextField_FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FNActionPerformed

    private void jTextField_LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LNActionPerformed

    private void jTextField_UNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UNActionPerformed

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_CancelButtonMouseClicked

    private void jTextField_EmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmActionPerformed

    private void jTextField_UN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UN2ActionPerformed

    private void jTextField_UN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UN3ActionPerformed

    private void jTextField_UN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UN4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UN4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel Enter;
    private javax.swing.JLabel Enter1;
    private javax.swing.JLabel Enter2;
    private javax.swing.JLabel Enter3;
    private javax.swing.JLabel Enter4;
    private javax.swing.JLabel Enter5;
    private javax.swing.JLabel Enter6;
    private javax.swing.JLabel Enterpw;
    private javax.swing.JLabel Enterpw1;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password2;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username2;
    private javax.swing.JLabel Username3;
    private javax.swing.JLabel Username4;
    private javax.swing.JLabel UserprofileIcon;
    private javax.swing.JLabel UserprofileIcon1;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel emial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_PASS;
    private javax.swing.JPasswordField jPasswordField_REPASS;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField_Em;
    private javax.swing.JTextField jTextField_FN;
    private javax.swing.JTextField jTextField_LN;
    private javax.swing.JTextField jTextField_UN;
    private javax.swing.JTextField jTextField_UN2;
    private javax.swing.JTextField jTextField_UN3;
    private javax.swing.JTextField jTextField_UN4;
    // End of variables declaration//GEN-END:variables
}
