/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregistration;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author user
 */
public class UserManagementForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserManagementForm.class.getName());

    /**
     * Creates new form UserManagementForm
     */
    public UserManagementForm() {
        initComponents();
        setLocationRelativeTo(null); // center form
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
       centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < jTable1.getColumnCount(); i++) {
       jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        FirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        FirstName1 = new javax.swing.JLabel();
        txtEmial = new javax.swing.JTextField();
        FirstName2 = new javax.swing.JLabel();
        txtDep = new javax.swing.JTextField();
        FirstName3 = new javax.swing.JLabel();
        txtSem = new javax.swing.JTextField();
        FirstName4 = new javax.swing.JLabel();
        txtGpa = new javax.swing.JTextField();
        LoadButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User_ID", "First Name", "Last Name", "Username", "Email", "Depart", "Sem", "GPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 30, 66));

        FirstName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name");

        txtFirstName.setBackground(new java.awt.Color(204, 204, 255));
        txtFirstName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtFirstName.setToolTipText("Enter your first name");
        txtFirstName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFirstName.addActionListener(this::txtFirstNameActionPerformed);

        LastName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name");

        txtLastName.setBackground(new java.awt.Color(204, 204, 255));
        txtLastName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtLastName.setToolTipText("Enter your lastname");
        txtLastName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLastName.addActionListener(this::txtLastNameActionPerformed);

        Username.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username: ");

        txtUsername.setBackground(new java.awt.Color(204, 204, 255));
        txtUsername.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtUsername.setToolTipText("Enter your username");
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        FirstName1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        FirstName1.setForeground(new java.awt.Color(255, 255, 255));
        FirstName1.setText("Email");

        txtEmial.setBackground(new java.awt.Color(204, 204, 255));
        txtEmial.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtEmial.setToolTipText("Enter your first name");
        txtEmial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmial.addActionListener(this::txtEmialActionPerformed);

        FirstName2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        FirstName2.setForeground(new java.awt.Color(255, 255, 255));
        FirstName2.setText("Department");

        txtDep.setBackground(new java.awt.Color(204, 204, 255));
        txtDep.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtDep.setToolTipText("Enter your first name");
        txtDep.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDep.addActionListener(this::txtDepActionPerformed);

        FirstName3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        FirstName3.setForeground(new java.awt.Color(255, 255, 255));
        FirstName3.setText("Semester");

        txtSem.setBackground(new java.awt.Color(204, 204, 255));
        txtSem.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtSem.setToolTipText("Enter your first name");
        txtSem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSem.addActionListener(this::txtSemActionPerformed);

        FirstName4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        FirstName4.setForeground(new java.awt.Color(255, 255, 255));
        FirstName4.setText("GPA");

        txtGpa.setBackground(new java.awt.Color(204, 204, 255));
        txtGpa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtGpa.setToolTipText("Enter your first name");
        txtGpa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGpa.addActionListener(this::txtGpaActionPerformed);

        LoadButton.setBackground(new java.awt.Color(0, 51, 255));
        LoadButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoadButton.setText("Load");
        LoadButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(102, 102, 255)));
        LoadButton.addActionListener(this::LoadButtonActionPerformed);

        UpdateButton.setBackground(new java.awt.Color(0, 153, 0));
        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(102, 255, 0), new java.awt.Color(102, 204, 0), new java.awt.Color(0, 153, 0)));
        UpdateButton.addActionListener(this::UpdateButtonActionPerformed);

        DeleteButton.setBackground(new java.awt.Color(204, 0, 0));
        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 51, 51)));
        DeleteButton.addActionListener(this::DeleteButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FirstName)
                        .addGap(5, 5, 5)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LastName)
                        .addGap(8, 8, 8)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Username)
                        .addGap(2, 2, 2)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FirstName3)
                    .addComponent(FirstName2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FirstName1)
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEmial, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(FirstName4))
                    .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSem, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstName4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void loadUsers() {

    ArrayList<User> users = UserDAO.getAllUsers();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    model.setRowCount(0); // clear table

    for (User u : users) {
        model.addRow(new Object[]{
            u.getId(),
            u.getFname(),
            u.getLname(),
            u.getUsername(),
            u.getEmail(),
            u.getDepartment(),
            u.getSem(),
            u.getGpa()
        });
    }
}
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
       
    int row = jTable1.getSelectedRow();

    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a user first");
        return;
    }

    try {
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String fname = txtFirstName.getText().trim();
        String lname = txtLastName.getText().trim();
        String uname = txtUsername.getText().trim();
        String email = txtEmial.getText().trim();
        String dept = txtDep.getText().trim();
        int sem = Integer.parseInt(txtSem.getText().trim());
        double gpa = Double.parseDouble(txtGpa.getText().trim());

        // Optional: additional validation
        if (fname.isEmpty() || lname.isEmpty() || uname.isEmpty() || email.isEmpty() || dept.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "All fields must be filled!", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (gpa < 0 || gpa > 4.0) {
            javax.swing.JOptionPane.showMessageDialog(this, "GPA must be between 0 and 4.0!", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean updated = UserDAO.updateUser(id, fname, lname, uname, email, dept, sem, gpa);
        if (updated) {
            javax.swing.JOptionPane.showMessageDialog(this, "User updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadUsers();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to update user. Check database connection.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semester and GPA must be valid numbers!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();

    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a user first");
        return;
    }
    try {
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            boolean deleted = UserDAO.deleteUser(id);
            if (deleted) {
                javax.swing.JOptionPane.showMessageDialog(this, "User deleted successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                loadUsers();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete user. Check database connection.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        // TODO add your handling code here:
            loadUsers();
    }//GEN-LAST:event_LoadButtonActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();

    if (row == -1) {
        return;
    }

    txtFirstName.setText(jTable1.getValueAt(row, 1).toString());
    txtLastName.setText(jTable1.getValueAt(row, 2).toString());
    txtUsername.setText(jTable1.getValueAt(row, 3).toString());
    txtEmial.setText(jTable1.getValueAt(row, 4).toString());
    txtDep.setText(jTable1.getValueAt(row, 5).toString());
    txtSem.setText(jTable1.getValueAt(row, 6).toString());
    txtGpa.setText(jTable1.getValueAt(row, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtEmialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmialActionPerformed

    private void txtDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepActionPerformed

    private void txtSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemActionPerformed

    private void txtGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserManagementForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel FirstName1;
    private javax.swing.JLabel FirstName2;
    private javax.swing.JLabel FirstName3;
    private javax.swing.JLabel FirstName4;
    private javax.swing.JLabel LastName;
    private javax.swing.JButton LoadButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDep;
    private javax.swing.JTextField txtEmial;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSem;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}



