CREATE DATABASE STUDENT;
USE STUDENT;
CREATE TABLE students(
u_id INT PRIMARY KEY AUTO_INCREMENT,
u_fname VARCHAR(50) NOT NULL,
u_lname VARCHAR(50) NOT NULL,
u_username VARCHAR(50) UNIQUE NOT NULL,
u_pass VARCHAR(20) NOT NULL,
u_email VARCHAR(50) UNIQUE NOT NULL,
u_depart VARCHAR(50) NOT NULL,
u_sem INT NOT NULL,
u_cgpa DECIMAL(3,2) NOT NULL
);